apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-cicd-deployment
  namespace: automation
  labels:
    app: automation-cicd
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: automation-cicd
  template:
    metadata:
      labels:
        app: automation-cicd
    spec:
      containers:
        - name: automation-cicd-container
          image: kanchon/automation-cicd:latest
          imagePullPolicy: Always  # <--- এটি নিশ্চিত করবে প্রতিবার নতুন কোড চেক করবে
          ports:
            - containerPort: 7777
          readinessProbe: # এই অংশটি অটোমেশনের জন্য দরকার
            httpGet:
              path: /test # কুবারনেটিস এই পাথে নক করে দেখবে অ্যাপ রেডি কি না
              port: 7777
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"



















#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: automation-cicd-deployment
#  namespace: automation
#  labels:
#    app: automation-cicd
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: automation-cicd
#  template:
#    metadata:
#      labels:
#        app: automation-cicd
#    spec:
#      containers:
#        - name: automation-cicd-container
#          image: kanchon/automation-cicd:latest
#          imagePullPolicy: Always
#          ports:
#            - containerPort: 7777
#          resources:
#            limits:
#              memory: "512Mi"
#              cpu: "500m"
#            requests:
#              memory: "256Mi"
#              cpu: "250m"
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: "prod"
