apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-cicd-deployment
  namespace: automation
  labels:
    app: automation-cicd
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: automation-cicd
  template:
    metadata:
      labels:
        app: automation-cicd
    spec:
      # ১. গ্রেসফুল শাটডাউন (পড বন্ধ হওয়ার আগে কাজ শেষ করার সময় দিবে)
      terminationGracePeriodSeconds: 30
      containers:
        - name: automation-cicd-container
          image: kanchon/automation-cicd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7777

          # ২. Readiness Probe (আপনারটা ঠিক আছে, শুধু সময়টা এডজাস্ট করা হয়েছে)
          readinessProbe:
            httpGet:
              path: /test
              port: 7777
            initialDelaySeconds: 20 # অ্যাপ্লিকেশন স্টার্ট হতে সময় দিলে এরর কম হয়
            periodSeconds: 10
            failureThreshold: 3

          # ৩. Liveness Probe (পড হ্যাং হয়ে গেলে অটো রিস্টার্ট করবে)
          livenessProbe:
            httpGet:
              path: /test
              port: 7777
            initialDelaySeconds: 40
            periodSeconds: 20

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"



















#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: automation-cicd-deployment
#  namespace: automation
#  labels:
#    app: automation-cicd
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: automation-cicd
#  template:
#    metadata:
#      labels:
#        app: automation-cicd
#    spec:
#      containers:
#        - name: automation-cicd-container
#          image: kanchon/automation-cicd:latest
#          imagePullPolicy: Always
#          ports:
#            - containerPort: 7777
#          resources:
#            limits:
#              memory: "512Mi"
#              cpu: "500m"
#            requests:
#              memory: "256Mi"
#              cpu: "250m"
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: "prod"
