apiVersion: v1
kind: Service
metadata:
  name: automation-cicd-service
  namespace: automation
spec:
  selector:
    app: automation-cicd
  type: NodePort
  ports:
    - port: 8099         # ক্লাস্টারের ভেতরে এক্সেস করার পোর্ট
      targetPort: 7777   # আপনার স্প্রিং বুট অ্যাপের পোর্ট
      nodePort: 30030    # ব্রাউজার থেকে এক্সেস করার পোর্ট (localhost:30080)