apiVersion: v1
kind: Service
metadata:
  name: automation-cicd-service
  namespace: automation
spec:
  selector:
    app: automation-cicd
  type: LoadBalancer # স্থায়ী সমাধানের জন্য টাইপ পরিবর্তন করা হয়েছে
  ports:
    - name: http
      protocol: TCP
      port: 8099         # এখন সরাসরি এই পোর্টে হিট দিবেন (http://localhost:8099)
      targetPort: 7777   # আপনার অ্যাপের ভেতরের পোর্টর্ট (localhost:30080)