apiVersion: v1
kind: Service
metadata:
  name: automation-cicd-service
  namespace: automation
spec:
  selector:
    app: automation-cicd
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8099
      targetPort: 7777
      nodePort: 30030 # ব্রাউজার থেকে এক্সেস করার পোর্ট (localhost:30080)